### PR TITLE
remove unused variables and functions

### PR DESCRIPTION
**Pull request by ralphtheninja**
@dominictarr I noticed some stuff that wasn't used. What do you say about adding `standard`?

### CODE REVIEW

**Comment by dominictarr** [comment]
Standard is way too anal, it's just really annoying. If it was just the things like this, it would be cool, but it like, won't let me have whitespace after the first line of a function, and errors about that are just a waste of my time. Heh, maybe could use like standard@1 and not latest standard ;)

That said, if a module I wrote becomes maintained primarily by the community or another person I'm not against it turning to standard, but I don't like standard if I'm still the main one writing code.

**Comment by dominictarr** [comment]
merged into 1.2.2.

**Comment by ralphtheninja** [comment]
> Heh, maybe could use like standard@1 and not latest standard ;)

I understand. What I like the most is finding unused stuff. Cheers!

**Comment by dominictarr** [comment]
I heard there was some talk about refactoring the "objective" things from standard (such as unused vars), i'd def use that.

**Comment by dominictarr** [comment]
hmm, maybe you could pipe standard through a thing that just removes the whitespace "errors"?

**Comment by ralphtheninja** [comment]
> hmm, maybe you could pipe standard through a thing that just removes the whitespace "errors"?

Get out of my brain haha! I was thinking about that today as well :)

**Pull request merged**
